### ISSUE TITLE
Nothing is working...

### ISSUE THREAD

**Issue by guytoothpick** [ShangguanXi/RusticDelight-Refabricated#6]
I'm terribly sorry to say this, but everything in this port doesn't work as it should. I'm not sure if it somehow has to do with other mods I have installed, but nothing from the port is craftable, cookable, or even obtainable in survival. The wild crops do spawn, they just don't drop anything. I saw the other report on how they couldn't get cotton to work. I'm terribly sorry if this comes across as very negative, but I wish you the best if you wish to fix these!

**Comment by ShangguanXi** [comment]
game version

**Comment by guytoothpick** [comment]
it's 1.21.1, sorry

**Comment by ShangguanXi** [comment]
it will be fixed on next version

**Comment by ShangguanXi** [comment]
fixed
